### ISSUE TITLE
I want to use Technical Analysis Widget

### ISSUE THREAD

**Issue by jinhuatai** [tradingview/widgets-examples#2]
Hi,
I want to use Technical Analysis Widget，But I can't find the relevant API and dome .
There is only embedded code on the page . How do I use it to show the financial product data in our project?

![image](https://user-images.githubusercontent.com/51358227/61853684-15f05700-aeef-11e9-8852-953fa5a98a77.png)

**Comment by timocov** [comment]
I believe this repo isn't about support for TradingView's widget. If you need a help - please contact support on www.tradingview.com.
